const DataSet = [
  {'age': 7, 'seriousness':4},
  {'age': 16, 'seriousness':4},
  {'age': 18, 'seriousness':2},
  {'age': 19, 'seriousness':3},
  {'age': 17, 'seriousness':3},
  {'age': 17, 'seriousness':4},
  {'age': 11, 'seriousness':4},
  {'age': 17, 'seriousness':2},
  {'age': 14, 'seriousness': 4},
  {'age': 5, 'seriousness': 5},
  {'age': 8, 'seriousness': 3},
  {'age': 13, 'seriousness': 2},
  {'age': 19, 'seriousness': 2},
  {'age': 21, 'seriousness': 2},
  {'age': 17, 'seriousness': 3},
  {'age': 12, 'seriousness': 2},
  {'age': 19, 'seriousness': 2},
  {'age': 17, 'seriousness': 1},
  {'age': 18, 'seriousness': 2},
  {'age': 11, 'seriousness': 4},
  {'age': 12, 'seriousness': 3},
  {'age': 8, 'seriousness': 3},
  {'age': 16, 'seriousness': 1},
  {'age': 17, 'seriousness': 3},
  {'age': 19, 'seriousness': 5},
  {'age': 10, 'seriousness': 3},
  {'age': 17, 'seriousness': 3},
  {'age': 13, 'seriousness': 2},
  {'age': 15, 'seriousness': 4},
  {'age': 7, 'seriousness': 3},
  {'age': 15, 'seriousness': 4},
  {'age': 4, 'seriousness': 4},
  {'age': 19, 'seriousness': 3},
  {'age': 10, 'seriousness': 4},
  {'age': 20, 'seriousness': 3},
  {'age': 19, 'seriousness': 3},
];

export default DataSet;
