export const DataSet = [
  {'age': 7, 'seriousness':4},
  {'age': 16, 'seriousness':4},
  {'age': 18, 'seriousness':2},
  {'age': 19, 'seriousness':3},
  {'age': 17, 'seriousness':3},
  {'age': 17, 'seriousness':4},
  {'age': 11, 'seriousness':4},
  {'age': 17, 'seriousness':2},
  {'age': 14, 'seriousness': 4},
  {'age': 5, 'seriousness': 5},
  {'age': 8, 'seriousness': 3},
  {'age': 13, 'seriousness': 2},
  {'age': 19, 'seriousness': 2},
  {'age': 21, 'seriousness': 2},
  {'age': 17, 'seriousness': 3},
  {'age': 12, 'seriousness': 2},
  {'age': 19, 'seriousness': 2},
  {'age': 17, 'seriousness': 1},
  {'age': 18, 'seriousness': 2},
  {'age': 11, 'seriousness': 4},
  {'age': 12, 'seriousness': 3},
  {'age': 8, 'seriousness': 3},
  {'age': 16, 'seriousness': 1},
  {'age': 17, 'seriousness': 3},
  {'age': 19, 'seriousness': 5},
  {'age': 10, 'seriousness': 3},
  {'age': 17, 'seriousness': 3},
  {'age': 13, 'seriousness': 2},
  {'age': 15, 'seriousness': 4},
  {'age': 7, 'seriousness': 3},
  {'age': 15, 'seriousness': 4},
  {'age': 4, 'seriousness': 4},
  {'age': 19, 'seriousness': 3},
  {'age': 10, 'seriousness': 4},
  {'age': 20, 'seriousness': 3},
  {'age': 19, 'seriousness': 3},
];


export const BirthBrainInjury = [
{'age': 0, 'seriousness': 4},
{'age': 0, 'seriousness': 4},
{'age': 0, 'seriousness': 4},
{'age': 0, 'seriousness': 5},
{'age': 0, 'seriousness': 5},
{'age': 0, 'seriousness': 5},
{'age': 0, 'seriousness': 5},
{'age': 0, 'seriousness': 5},
{'age': 0, 'seriousness': 4},
{'age': 0, 'seriousness': 5},
{'age': 0, 'seriousness': 5},
{'age': 0, 'seriousness': 5},
{'age': 0, 'seriousness': 5},
{'age': 0, 'seriousness': 4},
{'age': 0, 'seriousness': 4},
{'age': 0, 'seriousness': 5},
{'age': 0, 'seriousness': 5},
{'age': 1, 'seriousness': 4},
{'age': 0, 'seriousness': 5},
{'age': 0, 'seriousness': 5},
{'age': 0, 'seriousness': 5},
{'age': 0, 'seriousness': 4},
{'age': 0, 'seriousness': 5},
{'age': 0, 'seriousness': 5},
{'age': 0, 'seriousness': 5},
{'age': 0, 'seriousness': 4},
{'age': 0, 'seriousness': 4},
{'age': 0, 'seriousness': 5},
{'age': 0, 'seriousness': 4},
{'age': 0, 'seriousness': 5},
{'age': 0, 'seriousness': 5}];

export const HighLevelSpinalInjury = [
{'age': 17, 'seriousness': 5},
{'age': 7	, 'seriousness': 4},
{'age': 20, 'seriousness': 4},
{'age': 11, 'seriousness': 4},
{'age': 18, 'seriousness': 5},
{'age': 20, 'seriousness': 5},
{'age': 11, 'seriousness': 5},
{'age': 9	, 'seriousness': 4},
{'age': 11, 'seriousness': 4},
{'age': 17, 'seriousness': 4},
{'age': 17, 'seriousness': 5},
{'age': 18, 'seriousness': 5},
{'age': 5	, 'seriousness': 4},
{'age': 9	, 'seriousness': 4},
{'age': 16, 'seriousness': 5},
{'age': 16, 'seriousness': 5},
{'age': 13, 'seriousness': 5},
{'age': 14, 'seriousness': 5},
{'age': 13, 'seriousness': 4},
{'age': 8	, 'seriousness': 5 }];


export const KneeInjury = [
{'age': 19, 'seriousness' : 2},
{'age': 13, 'seriousness' : 1},
{'age': 3, 'seriousness' : 3},
{'age': 4, 'seriousness' : 2},
{'age': 8, 'seriousness' : 1},
{'age': 12, 'seriousness' : 1},
{'age': 15, 'seriousness' : 2},
{'age': 13, 'seriousness' : 2},
{'age': 15, 'seriousness' : 1},
{'age': 2, 'seriousness' : 1},
{'age': 12, 'seriousness' : 1},
{'age': 17, 'seriousness' : 1},
{'age': 15, 'seriousness' : 2},
{'age': 16, 'seriousness' : 2},
{'age': 0, 'seriousness' : 1},
{'age': 9, 'seriousness' : 2},
{'age': 19, 'seriousness' : 2},
{'age': 20, 'seriousness' : 2},
{'age': 13, 'seriousness' : 2},
{'age': 18, 'seriousness' : 2},
{'age': 11, 'seriousness' : 1}];


export const SeriousBurnsInjury = [
{'age': 11, 'seriousness' :2},
{'age': 19, 'seriousness' :2},
{'age': 12, 'seriousness' :3},
{'age': 2, 'seriousness' :2},
{'age': 0, 'seriousness' :3},
{'age': 5, 'seriousness' :2},
{'age': 5, 'seriousness' :2},
{'age': 15, 'seriousness' :3},
{'age': 15, 'seriousness' :2},
{'age': 3, 'seriousness' :2},
{'age': 10, 'seriousness' :3},
{'age': 15, 'seriousness' :2},
{'age': 21, 'seriousness' :2},
{'age': 1, 'seriousness' :3},
{'age': 1, 'seriousness' :3},
{'age': 1, 'seriousness' :4},
{'age': 18, 'seriousness' :3},
{'age': 19, 'seriousness' :3},
{'age': 13, 'seriousness' :2},
{'age': 2, 'seriousness' :3},
{'age': 9, 'seriousness' :2}];